// Package contracts generates the browser's JSON Schema boundary from the
// Go response DTOs that the daemon actually serializes.
package contracts

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/invopop/jsonschema"
	"github.com/m-cain/autoboard/internal/app"
)

//go:generate go run ../../cmd/autoboard-schema ../../packages/contracts/generated-go ../../packages/contracts/src/generated/browser-schemas.ts

type TicketList struct {
	Tickets []app.Ticket `json:"tickets"`
}

func Documents() (map[string][]byte, error) {
	values := map[string]any{
		"activity-event.schema.json": app.ActivityEvent{},
		"project-board.schema.json":  app.ProjectBoard{},
		"project-list.schema.json":   app.ProjectList{},
		"ticket-detail.schema.json":  app.TicketDetail{},
		"ticket-list.schema.json":    TicketList{},
	}
	documents := make(map[string][]byte, len(values))
	for name, value := range values {
		reflector := &jsonschema.Reflector{
			Anonymous:      true,
			DoNotReference: false,
		}
		schema := reflector.Reflect(value)
		encoded, err := json.Marshal(schema)
		if err != nil {
			return nil, fmt.Errorf("encode %s: %w", name, err)
		}
		var raw any
		if err := json.Unmarshal(encoded, &raw); err != nil {
			return nil, fmt.Errorf("decode %s for draft conversion: %w", name, err)
		}
		document, err := json.MarshalIndent(draft7Schema(raw), "", "  ")
		if err != nil {
			return nil, fmt.Errorf("encode %s: %w", name, err)
		}
		documents[name] = append(document, '\n')
	}
	return documents, nil
}

func draft7Schema(value any) any {
	switch typed := value.(type) {
	case []any:
		converted := make([]any, len(typed))
		for index, nested := range typed {
			converted[index] = draft7Schema(nested)
		}
		return converted
	case map[string]any:
		converted := make(map[string]any, len(typed))
		for key, nested := range typed {
			if key == "$defs" {
				key = "definitions"
			}
			if key == "$schema" {
				converted[key] = "http://json-schema.org/draft-07/schema#"
				continue
			}
			if numericSchemaKeyword(key) {
				if encoded, ok := nested.(string); ok {
					if integer, err := strconv.ParseInt(encoded, 10, 64); err == nil {
						converted[key] = integer
						continue
					}
					if number, err := strconv.ParseFloat(encoded, 64); err == nil {
						converted[key] = number
						continue
					}
				}
			}
			converted[key] = draft7Schema(nested)
		}
		return converted
	case string:
		return strings.ReplaceAll(typed, "#/$defs/", "#/definitions/")
	default:
		return value
	}
}

func numericSchemaKeyword(value string) bool {
	switch value {
	case "multipleOf",
		"maximum",
		"exclusiveMaximum",
		"minimum",
		"exclusiveMinimum",
		"maxLength",
		"minLength",
		"maxItems",
		"minItems",
		"maxContains",
		"minContains",
		"maxProperties",
		"minProperties":
		return true
	default:
		return false
	}
}

func TypeScriptModule() ([]byte, error) {
	documents, err := Documents()
	if err != nil {
		return nil, err
	}
	names := map[string]string{
		"activity-event.schema.json": "ActivityEventSchema",
		"project-board.schema.json":  "ProjectBoardSchema",
		"project-list.schema.json":   "ProjectListSchema",
		"ticket-detail.schema.json":  "TicketDetailSchema",
		"ticket-list.schema.json":    "TicketListSchema",
	}
	filenames := make([]string, 0, len(names))
	for name := range names {
		filenames = append(filenames, name)
	}
	slices.Sort(filenames)
	var module strings.Builder
	module.WriteString(
		"// Code generated by go generate ./internal/contracts; DO NOT EDIT.\n\n",
	)
	module.WriteString(
		"import type { JSONSchema } from \"json-schema-to-ts\";\n\n",
	)
	for index, filename := range filenames {
		document := strings.TrimSpace(string(documents[filename]))
		fmt.Fprintf(
			&module,
			"export const %s = %s as const satisfies JSONSchema;\n",
			names[filename],
			document,
		)
		if index < len(filenames)-1 {
			module.WriteByte('\n')
		}
	}
	return []byte(module.String()), nil
}

func Write(directory string, modulePath string) error {
	documents, err := Documents()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create schema directory: %w", err)
	}
	names := make([]string, 0, len(documents))
	for name := range documents {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		path := filepath.Join(directory, name)
		if err := os.WriteFile(path, documents[name], 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	module, err := TypeScriptModule()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(modulePath), 0o755); err != nil {
		return fmt.Errorf("create TypeScript schema directory: %w", err)
	}
	if err := os.WriteFile(modulePath, module, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", modulePath, err)
	}
	return nil
}

func Check(directory string, modulePath string) error {
	documents, err := Documents()
	if err != nil {
		return err
	}
	for name, expected := range documents {
		path := filepath.Join(directory, name)
		current, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated schema %s: %w", path, err)
		}
		if !bytes.Equal(current, expected) {
			return fmt.Errorf(
				"%s is stale; run go generate ./internal/contracts",
				path,
			)
		}
	}
	expectedModule, err := TypeScriptModule()
	if err != nil {
		return err
	}
	currentModule, err := os.ReadFile(modulePath)
	if err != nil {
		return fmt.Errorf("read generated module %s: %w", modulePath, err)
	}
	if !bytes.Equal(currentModule, expectedModule) {
		return fmt.Errorf(
			"%s is stale; run go generate ./internal/contracts",
			modulePath,
		)
	}
	return nil
}
